name: dbx_platform
description: An unofficial dropbox platform package.

version: 1.1.7+9

repository: https://github.com/LiveUser/dbx_platform

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  sexy_api_client: ^0.0.4+4

dev_dependencies:
  test:
  lints: ^1.0.0